language: python
python:
    - "2.7"
    - "3.5"
    - "3.6"

addons:
    apt:
        packages:
            - gyp

services:
    - postgresql
    - redis

install:
    - pip install -r requirements.txt
    - pip install .

env:
    global:
        - RDBMS_URI='postgres://postgres@localhost/travis_ci_test'

before_script:
    - echo 'Etc/UTC' | sudo tee /etc/timezone
    - sudo dpkg-reconfigure --frontend noninteractive tzdata
    - psql -c 'create database travis_ci_test;' -U postgres
    # Create tables
    - nvm install lts/*
    - npm config set spin false
    - npm i -g npm
    - npm i -g bunyan mocha node-gyp tslint typings typescript
    - git clone https://github.com/offscale/healthplatform-nodejs-rest-api
    - pushd glaucoma-risk-calculator-rest-api
    - typings i
    - npm ci
    - tsc
    - npm test || true  # We don't actually care about tests passing, just tables
    - popd
    - rm -rf https://github.com/offscale/healthplatform-nodejs-rest-api

script:
    - pip install coveralls
    - coverage run --source='healthplatform_stats_rest_api' setup.py test

after_success:
    - coveralls
